// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "carlo", input: never, result: CarloResponse } | 
        { key: "login", input: never, result: string } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type User = { name: string; age: number; alive: boolean }

export type CarloResponse = { user: User; greeting: string }
