// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "carlo", input: never, result: CarloResponse } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "register", input: LoginInput, result: UserResponse },
    subscriptions: never
};

export type CarloResponse = { user: UserResponse; greeting: string }

export type UserResponse = { name: string; age: number; alive: boolean }

export type LoginInput = { username: string; email: string | null; password: string }
