set dotenv-load

default:
    just --list

# migrate-create *name:
#     diesel migration generate {{name}}

# migrate-up:
#     diesel migration run --database-url $DATABASE_URL

# migrate-down:
#     diesel migration revert

db-studio:
    bunx prisma studio

db-migrate:
    bunx prisma migrate deploy

db-migrate-dev:
    bunx prisma migrate dev --schema ./prisma

# Generates entities for Rust interfacing.
db-generate:
    sea-orm-cli generate entity --database-url $DATABASE_URL -o entity/src/entities --with-serde serialize --model-extra-derives 'specta::Type'

# Simple OS-specific command (Just a sample)
list:
    #!/usr/bin/env sh
    if [ "{{os()}}" = "windows" ]; then
        echo "Listing on Windows"
        dir
    else
        echo "Listing on Unix"
        ls -l
    fi

[windows]
listc:
    echo 'I am windows'
    dir

[macos]
listc:
    echo 'I am mac'
    ls -l
